# Data Analysis with Python

Prerequisites:
1. Basic programming with python- data types,syntax...

What to expect in this course
1. Handling data with numpy and pandas- learn to import, read, clean and prepare data for analysis
    numpy is great for data analysis, pandas is great for data manipulation
2. Data Visualizations-   Matplotlib and Seaborn, learning how to create charts, graphs, and plots that tell the story behind your data.
3. Exploratory Data Analysis- incovering patterns in data

How I teach/learn
1. Interactive- 
Basics, Example....practical questions

### 1. Setting up and working with Virtual Environments

### 2. Numpy Fundamentals

#### 2.1 Numpy Arrays

#### 2.2 Creating an array from Scratch

In [1]:
import numpy as np

In [2]:
#making an array from lists
my_list=[1,2,3,4,5,6,]
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [3]:
np.array([4,5,6,7,8,9,])

array([4, 5, 6, 7, 8, 9])

In [4]:
#an array of zeros
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [5]:
#an arrays of ones
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
#initilaiza using random numbers
np.random.rand(4,2)

array([[0.63763384, 0.15394208],
       [0.95965975, 0.69286424],
       [0.07496561, 0.30190627],
       [0.09142798, 0.94487039]])

In [7]:
np.random.randint(100,size=(4,2))

array([[61, 83],
       [91, 45],
       [ 4,  5],
       [40, 53]], dtype=int32)

In [8]:
a=np.full((2,2),8)
a

array([[8, 8],
       [8, 8]])

In [9]:
np.full_like(a,4)

array([[4, 4],
       [4, 4]])

In [10]:
np.random.randint(7,50,size=(2,7))

array([[43, 26, 30, 26,  8, 15, 10],
       [44, 27, 14, 35, 48, 26, 24]], dtype=int32)

Lesson #2
-Attributes
-Indexing & slicing arrays
-Universal functions
-Aggregate functions
-Broadcasting

#### 2.3 Attributes of an array

In [15]:
#ndarray.ndim- outputs no.of dimensions of the array
#ndarray.shape- no of row, no. columns
#ndarray.size-total no. of elements- rows*columns
#ndarray.dtype- data type of all elements in the array

In [17]:
arr=np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
arr.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
arr2=np.full((2,4,5),10)
arr2

array([[[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]])

In [23]:
arr2.ndim

3

In [24]:
arr2.size

40

In [25]:
arr2.dtype

dtype('int64')

In [26]:
arr2.shape

(2, 4, 5)

In [19]:
arr.ndim

1

#### 2.4 Basic operations on numpy arrays

Indexing

In [65]:
jemma=np.array([20,34,56,89])
jemma

array([20, 34, 56, 89])

In [66]:
#arr[start:stop]
jemma[1:3]

array([34, 56])

In [68]:
jemma[0:2]

array([20, 34])

In [89]:
ann6=np.array([20,34,67,45,98,35,98,12,50,90])
ann6

array([20, 34, 67, 45, 98, 35, 98, 12, 50, 90])

In [90]:
ann6.reshape(2,5)

array([[20, 34, 67, 45, 98],
       [35, 98, 12, 50, 90]])

In [96]:
ann6[:,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [40]:
jemma[2]

np.int64(56)

In [42]:
ann=np.arange(8)
ann

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
ann[5]

np.int64(5)

In [107]:
arr4=np.array(
    [
    [10, 20,30,57],
    [45, 78,60,54],
    [12,79,53,28]
]
)
arr4

array([[10, 20, 30, 57],
       [45, 78, 60, 54],
       [12, 79, 53, 28]])

In [108]:
#arr[row,colum]
arr4[1,:]

array([45, 78, 60, 54])

In [110]:
#arr[row,column]
arr4[1:3,1:3]

array([[78, 60],
       [79, 53]])

In [98]:
#arr[row,column]
arr4[0,:]

array([10, 20, 30, 57])

In [99]:
arr4[:,0]

array([10, 45])

In [102]:
arr4[:,1:3]

array([[20, 30],
       [78, 60]])

In [106]:
arr4[1,2:4]

array([60, 54])

In [104]:
#arr4[rows,columns]
arr4[0,0:3]

array([10, 20, 30])

In [60]:
arr5=np.array(
    [
    [15, 20,34,12],
    [38, 78,54,80],
    [23,45,67,78]
]
)
arr5

array([[15, 20, 34, 12],
       [38, 78, 54, 80],
       [23, 45, 67, 78]])

In [63]:
arr5[0:2,2]

array([34, 54])

In [64]:
arr5[:,2]

array([34, 54, 67])

In [112]:
arr5=np.array([
    [
    [10, 20,30,57],
    [45, 78,60,54]
],
[
    [18,19,54,76],
    [12,14,56,78]
]
])
arr5

array([[[10, 20, 30, 57],
        [45, 78, 60, 54]],

       [[18, 19, 54, 76],
        [12, 14, 56, 78]]])

In [113]:
arr5[0,0,:]

array([10, 20, 30, 57])

In [116]:
arr5[1,:,1:3]

array([[19, 54],
       [14, 56]])

In [46]:
arr4


array([[[10, 20, 30, 57],
        [45, 78, 60, 54]],

       [[18, 19, 54, 76],
        [12, 14, 56, 78]]])

Slicing

Reshaping

#### 2.5 Universal functions
What do we mean by vectorization?
You are able to manipulate elements in an array one by one simultaneously

In [117]:
#adding numbers to elements in an array
arr5

array([[[10, 20, 30, 57],
        [45, 78, 60, 54]],

       [[18, 19, 54, 76],
        [12, 14, 56, 78]]])

In [118]:
np.add(arr5,5)

array([[[15, 25, 35, 62],
        [50, 83, 65, 59]],

       [[23, 24, 59, 81],
        [17, 19, 61, 83]]])

In [119]:
np.multiply(arr5,2)

array([[[ 20,  40,  60, 114],
        [ 90, 156, 120, 108]],

       [[ 36,  38, 108, 152],
        [ 24,  28, 112, 156]]])

In [120]:
np.power(arr5,2)

array([[[ 100,  400,  900, 3249],
        [2025, 6084, 3600, 2916]],

       [[ 324,  361, 2916, 5776],
        [ 144,  196, 3136, 6084]]])

In [124]:
np.cos(arr5)

array([[[-0.83907153,  0.40808206,  0.15425145,  0.89986683],
        [ 0.52532199, -0.85780309, -0.95241298, -0.82930983]],

       [[ 0.66031671,  0.98870462, -0.82930983,  0.82433133],
        [ 0.84385396,  0.13673722,  0.85322011, -0.85780309]]])

In [128]:
#aggregation function- suming, standard deviation,maximum,minimum
np.max(arr5, axis=0)

array([[18, 20, 54, 76],
       [45, 78, 60, 78]])

#Broadcasting

#vectorization in numpy-element wise operations

In [9]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,])
arr1-arr2

array([-3, -3, -3])

In [10]:
a=np.array([
    [1,2,3],
    [4,5,6]
])
b=[10,20,30]
a+b


array([[11, 22, 33],
       [14, 25, 36]])

In [1]:
import numpy as np
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [2]:
a

array([[0],
       [1],
       [2]])

In [3]:
b

array([0, 1, 2])

In [4]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

array([[30, 22, 29, 49, 19],
       [13, 42, 14, 24,  8],
       [29,  1, 20, 14, 48],
       [ 7, 26, 20,  5, 37]], dtype=int32)

Comparisons, Masks and Booleans

In [11]:
c=np.random.randint(50,size=(4,5))
c

array([[30,  0,  6, 33,  3],
       [34, 31,  0, 38, 17],
       [24, 13, 32, 44, 30],
       [26,  8,  5, 34,  9]], dtype=int32)

In [17]:
c != 30

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [20]:
#masks- filter the array based on a certain criteria
np.sum(c<30, axis=1)

array([3, 2, 2, 4])

In [21]:
np.sum(c<10)&(c>30)

array([[0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0]])

Fancy Indexing

In [24]:
d=np.arange(7)
d

array([0, 1, 2, 3, 4, 5, 6])

In [25]:
d[3]

np.int64(3)

In [26]:
e=np.array([10,20,39,48,56])
e

array([10, 20, 39, 48, 56])

In [29]:
ind=[0,2,4]
select_of_e= e[ind]


In [ ]:
e[0]
e[2]
e[4]

In [30]:
select_of_e

array([10, 39, 56])

In [31]:
#example of 2d Fancy indexing
f=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
row_ind=[0,2]
f[row_ind]

array([[1, 2, 3],
       [7, 8, 9]])

In [33]:
#arr[row_indices,column_indices]
row_ind=[0,2]
col_ind=[1,2]

f[row_ind,col_ind]


array([2, 9])

#Sorting

In [35]:
arr3=np.array([37,20,6,78,98])
arr3

array([37, 20,  6, 78, 98])

In [39]:
np.sort(arr3)


array([ 6, 20, 37, 78, 98])

In [40]:
arr4=np.random.randint(100,size=(5,5))
arr4

array([[52, 91,  3, 70, 24],
       [68, 34, 15, 74, 69],
       [79, 93, 32, 90,  6],
       [76, 27, 84, 62, 98],
       [14, 55, 46, 61, 11]], dtype=int32)

In [41]:
np.sort(arr4,axis=0)

array([[14, 27,  3, 61,  6],
       [52, 34, 15, 62, 11],
       [68, 55, 32, 70, 24],
       [76, 91, 46, 74, 69],
       [79, 93, 84, 90, 98]], dtype=int32)

In [42]:
np.sort(arr4,axis=1)

array([[ 3, 24, 52, 70, 91],
       [15, 34, 68, 69, 74],
       [ 6, 32, 79, 90, 93],
       [27, 62, 76, 84, 98],
       [11, 14, 46, 55, 61]], dtype=int32)

In [44]:
np.argsort(arr4,axis=1)

array([[2, 4, 0, 3, 1],
       [2, 1, 0, 4, 3],
       [4, 2, 0, 3, 1],
       [1, 3, 0, 2, 4],
       [4, 0, 2, 1, 3]])